### PR TITLE
Updates business line content to What we deliver content

### PR DESCRIPTION
**Pull request by awfrancisco**

### CODE REVIEW

**Comment by awfrancisco** [comment]
@JayFinch18F Can you take a look at this and merge if it's good?

**Comment by romkedehaan** [comment]
@awfrancisco done! Looks great. Thanks for updating this.

**Comment by romkedehaan** [comment]
Does anyone know how this get's to staging/production? @wslack ?

**Comment by awfrancisco** [comment]
@romkedehaan It's already live https://pages.18f.gov/intake/what-we-deliver/

**Comment by romkedehaan** [comment]
MAGIC.

**Pull request merged**
