### PR TITLE
Intro content

### PR DESCRIPTION
**Pull request by awfrancisco**

### CODE REVIEW

**Comment by wslack** [comment]
@StephaniePlageman did we want images on this page?

**Comment by StephaniePlageman** [comment]
@awfrancisco @wslack Yes we wanted to include pictures of Will and Stephanie (I think pulling them from the 18f site)

**Comment by wslack** [comment]
@awfrancisco how can we do this in a visually appealing way than two images stacked (like with text wrapping?)

**Comment by awfrancisco** [comment]
For sure. I'll push up a solution in a bit. We will have to merge it to see
what it looks like, but we'll get it right.

Sent from my iPhone

On Nov 24, 2015, at 9:58 AM, Will Slack notifications@github.com wrote:

@awfrancisco https://github.com/awfrancisco how can we do this in a
visually appealing way than two images stacked (like with text wrapping?)

**Comment by awfrancisco** [comment]
Added images. Let's merge and see how it looks.

**Comment by wslack** [comment]
@awfrancisco well, that didn't work out super well :P

**Comment by awfrancisco** [comment]
Working on it.

**Comment by wslack** [comment]
<3

**Pull request merged**
