### PR TITLE
fix image

### PR DESCRIPTION
**Pull request by awfrancisco**

### CODE REVIEW

**Comment by wslack** [comment]
merging but I think we'll want to replace with something higher quality in future!

**Comment by awfrancisco** [comment]
Yeah. Image is legible when my window is full screen, but pretty hard on smaller screens. Might be hard on a tablet.

**Comment by wslack** [comment]
Yep - the intent is to be transparent as much as we can, but I don't think
its worth the time to record the pieces into something responsive friendly
given that the text explains the process anyhow.

-W

_Will Slack_
Deputy Director, 18F Business Strategy

*18F https://18f.gsa.gov/ | OCSIT
http://www.gsa.gov/portal/category/25729 *

*| *

_GSA http://www.gsa.gov/portal/category/100000 | USA
http://beta.usa.gov/_
202 746 5385 <202.746.5385> (c) - _william.slack@gsa.gov
william.slack@gsa.gov_

**Comment by awfrancisco** [comment]
Sounds good.

**Pull request merged**
